version: '3.4'

services:
  db:
    image: harmonicus-db
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    build:
      context: .
      dockerfile: db/Dockerfile
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: harmonicus
      MYSQL_USER: harmonicus
      MYSQL_PASSWORD: harmonicus
      MYSQL_DATABASE: harmonicus
    ports:
      - 3306:3306
    networks:
      - harmonicus-network
    
  harmonicus:
    image: harmonicus
    build:
      context: .
      dockerfile: harmonicus/Dockerfile
    environment:
      TZ: America/Sao_Paulo
      ASPNETCORE_ENVIRONMENT: Production
    ports:
      - 44303:80
    depends_on:
      - db
    networks:
      - harmonicus-network
networks:
  harmonicus-network:
    driver: bridge
